apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: affinity-pod
spec:
  containers:
  - image: nginx
    name: pod
    ports:
    - containerPort: 80
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: environment
            operator: In
            values: 
            - production
            - test
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference: 
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
