apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-simplilearn
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: print-simplilearn
            image: alpine
            command: ['echo','hello','simplilearn']
          restartPolicy: Never
