apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-dep
spec: 
  replicas: 10
  selector:
    matchLabels: 
      app: sl
  template: 
    metadata: 
      labels: 
        app: sl
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
