apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpd
  name: httpd-custom
spec:
  containers:
  - env:
    - name: NAME
      value: sanjay
    - name: LOCATION
      value: WADIYA
    image: httpd
    name: httpd-custom
    ports:
    - containerPort: 1506
