apiVersion: v1
data:
  password: c2ltcGxpbGVhcm4=
kind: Secret
metadata:
  creationTimestamp: "2021-10-10T14:30:46Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:password: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-10-10T14:30:46Z"
  name: mysecret-pass
  namespace: default
  resourceVersion: "95034"
  uid: 5db3cc92-3853-4b08-a3b4-e4a0a4ec80cf
type: Opaque
