apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: node-selector1
spec:
  nodeSelector:
     environment: production
  containers:
  - image: nginx
    name: node-selector
    ports:
    - containerPort: 80
