apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: resource-limit
  name: resource-limit
spec:
  containers:
  - image: nginx
    name: resource-limit
    resources:
      requests:
        cpu: 0.5
      limits:
        cpu: 1
