apiVersion: v1
kind: Pod
metadata:
  labels:
    run: storage-pod
  name: storage-pod
spec:
  containers:
  - image: alpine
    name: storage-pod
    command: ["/bin/sh", "-c","shuf -n 1 -i 0-1000 >> /opt/number.out && sleep 100"]
    volumeMounts:
    - name: number-storage
      mountPath: /opt
  volumes:
  - name: number-storage
    hostPath:
      path: /tmp/data
      type: DirectoryOrCreate
