apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata: 
 name: csr-for-alice
spec: 
 groups: 
 - "system:authenticated"
 usages: 
 - client auth
 - digital signature
 - key encipherment
 signerName: kubernetes.io/kube-apiserver-client
 request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZUQ0NBVDBDQVFBd0VERU9NQXdHQTFVRUF3d0ZZV3hwWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFDMXkycGs5bVhGTUxxZFk5NDUvOVE3TkNVVzI0blVNaXRVWklRQWNXMWFFT3F2CnhuMmVOTGtOK0IybzRHY3lwa0pQZE1mN2dOMHpveWprazIydUc2dmpFbzNjYTRIOHppbnlvVzIxbWlMajdhWXAKejFybzFXSm9NT1BGcUlONlhsbGJxdVRqMU9nT3VzVmpwNmgrbWlBdm9UdXZJYVRkajVWOEJTaXZsbmlWRUcxbwpDMlZoZStaZXlKMXgzcXovR3NlZVVGWFZpZDg4dTc4V0Z5T2J5bndzY3FVUjg2dGh0UWxEaU1vN3lRWkxlWWVtCjdQTDdEcjkveWZKSzFUeHgxT01qaWk3MHRUc2pNUXNHd2I1R21CeGRpUTZXM2JMbU12MWwxeFFsVjBSaXkrRW8KdnFJTmNOVC8vKzNzNlBpZnFiSzR1cnhRTzlma21RTU9zdlFHN1NSSkFnTUJBQUdnQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFKMlA3VjVoc2x4TDhoWkYxblRiWkJEcFMxc1gzWnFHQUxRV09TZDdSZWgzZ2hMV1kva215CmxqMjkxWjQ0c3d2aCtKN0twQWRTVkxZUW50Mi9TREl1N3VvVGIzR3FtaUMyUngrQ3lyckIyTFNXVTRIYmJ1cDEKMTdDZXNhTG44NlVUVlZFVkhiVTAwUHVnOUdQUEQ2YTNlVFplRU5mWnVKV1Mwb2VjSDZudkhhdzErUExTbmZpVQpBdXkybDA5bU5mZ2pKc0tsMURTMU1LRzNpT2VyQysycVFia1N0dnVaWlJFa3RYZlpoaUFmei8rQ1g2ejlpUWMwCkdwTnNUVEx0a2RkYm04Y2hYRXJ0UmJIT01QOVJGYkdoaW1BRVVvYlorVmo2bUdiNWFRcS85ZEEzVitGOFBNRksKYkRyOFpxcGo0bE1nYm1xQ2VwU3l6T0lYUytyMGVCTjB0UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
