apiVersion: v1
kind: Pod
metadata:
  name: pv-pvc
spec:
  containers:
  - image: nginx
    name: nginx-custom-webapp
    ports:
    - containerPort: 80
    volumeMounts: 
    - name: mywebpage
      mountPath: /usr/share/nginx/html
  volumes: 
  - name: mywebpage
    persistentVolumeClaim: 
     claimName: pvc1

