apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ['pods']
  verbs: ['get','list','create']
- apiGroups: [""]
  resources: ['ConfigMap']
  verbs: ['get','list','create','delete']
