apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-custom-webapp
  name: nginx-custom-webapp
spec:
  containers:
  - image: nginx
    name: nginx-custom-webapp
    ports:
    - containerPort: 80
    volumeMounts: 
    - name: mywebpage
      mountPath: /usr/share/nginx/html
  volumes: 
  - name: mywebpage
    configMap:
      name: customwebpage 
      items: 
      - key: index.html
        path: index.html
