apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: rootpassword
    - name: MYSQL_DATABASE
      value: simplilearn
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef: 
         name: mysecretpass
         key: password
    image: mysql
    name: mysql
    ports:
    - containerPort: 3306
